Update the service and if update fails rollback the service

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -47,8 +47,14 @@ jobs:
           username: ${{ secrets.EC2_USERNAME }}
           key: ${{ secrets.EC2_KEY }}
           script: |
+            # Pull the Image from docker hub
             sudo docker pull ${{ secrets.DOCKERHUB_USERNAME }}/yii2-app:${{ env.TAG_VERSION }}
-            sudo docker service update --image ${{ secrets.DOCKERHUB_USERNAME }}/yii2-app:${{ env.TAG_VERSION }}  yii2app
+            # Update the service
+            sudo docker service update --image ${{ secrets.DOCKERHUB_USERNAME }}/yii2-app:${{ env.TAG_VERSION }}  yii2app_yii2
+            # Rollback the service if update failed
+            if [ $? -ne 0 ]; then
+              docker service update --rollback yii2app_yii2
+            fi
             
 
 
